# Generated on Fri Mar 4 10:18:45 2021
# Modified on mini-cheetah-defaults.yaml
__collection-name__: robot-parameters

controller_dt     : 0.002
control_mode      : 6
#myValue           : 1010
stand_kd_cartesian: [30,30,30]
stand_kp_cartesian: [1000, 1000, 1000]
recovery_kp: [380,380,380]
recovery_kd: [15,25,25]
#testValue         : 111
foot_height_sensor_noise      :  0.001
foot_process_noise_position   :  0.002
foot_sensor_noise_position    :  0.001
foot_sensor_noise_velocity    :  0.1
imu_process_noise_position    :  0.02
imu_process_noise_velocity    :  0.02
kpCOM: [50,50,50]
kdCOM: [10,10,10]
kpBase: [300,200,100]
kdBase: [20,10,10]

## In upboard, cheater_mode must be 0, and use_rc should be 1,
## or YOU MAY MEET SEGMENT FAULT (CORE DUMP)! --WYN
cheater_mode      : 0
#cheater_mode      : 1
# use_rc: 1
use_rc: 0